export const COLOR_TOKENS = {
  "coral-orange": "#E46846",
  "slate-grey": "#1E1E1E",
  white: "#FFFFFF",
  "coral-orange-soft": "#F3C9BC",
  "coral-orange-wash": "#FAE7E1",
  "coral-orange-hover": "#D85C3A",
  "coral-orange-active": "#C85031",
  "ink-900": "#1E1E1E",
  "ink-700": "#4B4B4B",
  "ink-500": "#6F6F6F",
  "ink-300": "#B9B1AA",
  "ink-200": "#D9D2CB",
  "ink-100": "#ECE7E2",
  paper: "#F7F3EE",
  canvas: "#FBF8F5",
  "chalk-pink": "#F2A7BE",
  daffodil: "#FFD168",
  pistachio: "#AEE7C3",
  "windjammer-blue": "#61A5DF",
  success: "#5DAE71",
  "success-soft": "#E3F4E8",
  warning: "#E4A93A",
  "warning-soft": "#FFF1CC",
  danger: "#D85A52",
  "danger-soft": "#FCE6E3",
  border: "#D9D2CB",
  "border-strong": "#B9B1AA",
  "text-primary": "#1E1E1E",
  "text-secondary": "#4B4B4B",
  "text-disabled": "#6F6F6F",
  surface: "#FFFFFF",
  "surface-alt": "#F7F3EE",
  "page-background": "#FBF8F5",
} as const;

export const TYPOGRAPHY_TOKENS = {
  H1: {
    family: "var(--font-zilla-slab)",
    size: "60px",
    weight: 400,
    lineHeight: 1,
    letterSpacing: "0",
  },
  "sub-header-medium": {
    family: "var(--font-zilla-slab)",
    size: "24px",
    weight: 500,
    lineHeight: 1.45,
    letterSpacing: "0.5px",
  },
  "body-medium": {
    family: "var(--font-titillium-web)",
    size: "18px",
    weight: 400,
    lineHeight: 1.4,
    letterSpacing: "0",
  },
} as const;
